### ISSUE TITLE
VREG($01) Text  Corruption 

### ISSUE THREAD

**Issue by jebielak** [uli/basicengine-firmware#16]
VREG($01) causes all text printing to be corrupted after it's called. Tryed it both as
PRINT VREG($01)
A=VREG($01)

**Comment by konimaru** [comment]
Opcode $01 is in fact **Write Status Register**. Reading is $05 (which requires a f/w update).

**Comment by konimaru** [comment]
Once pull request #19 is approved this issue should be fixed (works for me).
