### ISSUE TITLE
RENUM does not check for RESTORE command and change the line number

### ISSUE THREAD

**Issue by bitartrate** [uli/basicengine-firmware#21]
When using RENUM does not check for RESTORE commands to change the line number it points to.  Would like it to function as it does for GOTO commands.

**Comment by konimaru** [comment]
Fixed in my branch despite having messed up the commit comment. It's still early here :)

**Comment by bitartrate** [comment]
I saw that you had made that commit right before I went to bed.  I knew what you meant ;)
I have verified that your fix to RENUM does interact with RESTORE correctly now.  Thank you!

**Comment by uli** [comment]
Please do not close bugs until they have been fixed and tested in _this_ repository.

**Comment by bitartrate** [comment]
Sorry about that Uli.  I'm understanding the workflow slowly but surely.

**Comment by uli** [comment]
FIxed in commit ee38433d5b074dc01200ef0ef4a74633959c79cf. Please close if it works now.

**Comment by bitartrate** [comment]
I have compiled today and verified it works as intended.  Thank you.
