### ISSUE TITLE
SAVE BG 0 TO "filename.bg" is returning a syntax error (exp numeric expr)

### ISSUE THREAD

**Issue by bitartrate** [uli/basicengine-firmware#34]
SAVE BG 0 TO "filename.bg"  is returning a syntax error (exp numeric expr)
I defined BG 0 TILES 16,14 SIZE 16,16
I formed the expression: SAVE BG 0 to "filename.bg" TILES 16,14 SIZE 16,16
it then asks for a numeric expression after the SIZE attribute.

**Comment by konimaru** [comment]
The way the code is written the command works as:
```
save bg "filename.bg" 0 to
```
IOW, parameters are grabbed in the wrong order.

**Comment by konimaru** [comment]
While looking at this I was wondering whether loading should be more like e.g.:
```
load bg 0 from "filename.bg"
```
Just a thought ...
