### ISSUE TITLE
RECT command is inconsistent

### ISSUE THREAD

**Issue by konimaru** [uli/basicengine-firmware#37]
fill colour == -1
- rectangle is one pixel short in each direction, e.g.
  - ```RECT100,100,102,102,200,-1``` only gives me 2x2 pixels

fill color != -1
- x dimension is now correct but height is still one short (3 by 2 with the example above)
- fill colour is in fact line colour
- I'd expect the border still to be drawn in line colour, this isn't the case
- special cases **w=0 || h=0** and **w=0 && h=0** are not handled

**Comment by bitartrate** [comment]
I thought I was seeing this but I was always drawing big rectangles and was not sure I could trust my eyes.  I have confirmed your bug.

**Comment by uli** [comment]
I'll assume this works now.

**Comment by konimaru** [comment]
Works for me. Ta
