### ISSUE TITLE
SDL version pixel graphics color bug

### ISSUE THREAD

**Issue by bitartrate** [uli/basicengine-firmware#41]
This affects LINE, CIRCLE, RECT, and PSET commands.  The color parameter only outputs a shade of blue no matter what value is given between 0-255.  The same bug exists in palette 0 and 1.  
However the COLOR and GPRINT work as intended.

**Comment by bitartrate** [comment]
If you fill the screen with random lines and colors then SAVE PCX the resulting .pcx file does save the colors as can be seen in a paint program.

**Comment by uli** [comment]
Please check if that fixes the issue.

Also, please open another issue for the SAVE PCX bug, it's unrelated.

**Comment by bitartrate** [comment]
What works:  color, the border and fill color of both CIRCLE and RECT work.

Minor issue:
CIRCLE: if you choose a radius that will draw the circle outside the screen boundary SDL closes BE window.
Good Job!

**Comment by bitartrate** [comment]
I'm sorry the SAVE PCX was informational not a bug report.

**Comment by uli** [comment]
The crash should be fixed now, so I will close this.
