### ISSUE TITLE
space + Enter = syntax error 

### ISSUE THREAD

**Issue by konimaru** [uli/basicengine-firmware#43]
Pressing enter on an empty line awards me with a linefeed. OK. Any number of spaces before that results in a(n unexpected) syntax error. NG

**Comment by konimaru** [comment]
I'm aware that the first case isn't invoking the tokenizer but having entered an empty line shouldn't be punished this hard :)

**Comment by uli** [comment]
I hate users... :)

Please check if it works for you now.

**Comment by konimaru** [comment]
Confirmed working.
