### ISSUE TITLE
Missinterpreting variable names beginning with keywords

### ISSUE THREAD

**Issue by Bluescreen2001** [uli/basicengine-firmware#46]
When using variable names that beginns with BASIC keywords they got interpreted as keywords. This ist during runtime of the BASIC program and also during loading it.

Example:
`dimension = 42`  gives an error because it interprets DIM ension = 42
`dmension = 42` is ok

This happens also in the middle of the line:

`x = sprite_x + z`  gives x = SPRITE x + z

**Comment by uli** [comment]
That is not a bug, but I fixed it anyway. :)
See https://betest.freeflarum.com/d/35-syntax-changes for details.
