### ISSUE TITLE
SDL fullscreen (switch '-f') needs a way to exit back to host OS desktop

### ISSUE THREAD

**Issue by bitartrate** [uli/basicengine-firmware#47]
When in fullscreen mode in the SDL BASIC Engine there is no way to cleanly close out of it back to the host OS desktop.  Something like an immediate mode EXIT command.

**Comment by bitartrate** [comment]
I like the SYSTEM command.  This is kind of a little thing but would it be possible to make SYSTEM reduce back to a window?  My use case would be to have Engine BASIC documentation loaded on the host and be able to go back and forth from fullscreen to refer to it without closing BE/SDL.

**Comment by uli** [comment]
I think a keyboard shortcut is more useful for that.

**Comment by uli** [comment]
So does Alt-Return resolve your issue then?

**Comment by bitartrate** [comment]
Uli, that is perfect!  Thank you.
To recap we now have SYSTEM command to close the SDL down.
<alt-return> to switch between fullscreen and windowed mode.
