### ISSUE TITLE
Add toolchain support for Fedora

### ISSUE THREAD

**Issue by chrysophylax** [uli/basicengine-firmware#5]
This can easily run on modern Fedora Linux systems if the installpackages and installpackages_hosted shell scripts are modified to call the Fedora package manager `dnf` with the following package substitutions:

## ttbasic/scripts/installpackages.sh
* asciidoc
* glibc-devel
* ncurses-devel
* gperf 
* python2-pyserial 
* ctags 
* flex 
* bison

## ttbasic/scripts/installpackages_hosted.sh
* libstdc++-devel
* SDL-devel

A possible way to check if the current system is running Fedora, `lsb_release -is` could be used as a test.

**Comment by uli** [comment]
Merged.
