### ISSUE TITLE
SOUND command could use a volume parameter

### ISSUE THREAD

**Issue by bitartrate** [uli/basicengine-firmware#51]
The SOUND command could use a volume parameter.  While working with the command I have found myself really wanting for different volumes of the sounds I trigger.

**Comment by uli** [comment]
Velocity is the volume.

**Comment by bitartrate** [comment]
I understand now.  I had interpreted the documentation to mean 0/off and 1/on.  I have confirmed that a decimal range between 0 and 1 if volume control. Thank you.
