### ISSUE TITLE
Enhancement: Save Without Line Numbers

### ISSUE THREAD

**Issue by OzHawk** [uli/basicengine-firmware#84]
It would be really nice if it was possible to save a file from the command line without it saving the line numbers.

When I edit a program in a text editor, I don't want to use line numbers as it makes it easier to shuffle bits around, and also promotes good naming habits for Labels.  When I load that program into memory, BE NG allocates the lines line numbers.  For a start, these line numbers are consecutive, making it difficult to add new lines from the command line (You can use the `renumber` command to make space between the other lines.  But if I then save that program from the command line, it gets saved with the line numbers, even though I loaded it without them to start with.

An optional parameter that indicated no line numbers would solve this...you'd only need the line numbers for those lines that were a destination label.  OK, so that makes it sound really difficult to implement, but I still think the idea is sound.

`save "myprogram.bas" -n`

**Comment by uli** [comment]
That has since been implemented as "SAVE <name> LINE OFF".
