### ISSUE TITLE
Scrolling: Bottom Line Not Overwritten

### ISSUE THREAD

**Issue by OzHawk** [uli/basicengine-firmware#85]
When scrolling a long program listing up and then down (or down and then up...depends on perspective) the bottom line is not overwritten.
Once the bottom line contains text, it seems to remain there.  `edit` does not clear it.  `cls` clears the bottom line.

It appears that the bottom line is populated when scrolling up, but not when scrolling down.

It may be caused by the fact that the bottom line is not a whole 8 pixels high.

`phys_mode=4`
`csize(0) = 80`
`csize(1) = 33`
`psize(0) = 480`
`psize(1) = 270`
`psize(2) = 540`

**Comment by uli** [comment]
This was fixed in 7971830168bbcaa5e8e992ee6412b72bd57a9ee2 ("tvutil: do not leave junk below the end of the text screen").
