### ISSUE TITLE
EDIT command crashes basicengine-firmware-default-v0.88-alpha-346-g4d5b

### ISSUE THREAD

**Issue by bitartrate** [uli/basicengine-firmware#9]
Hi Uli,

I hope all is well on your end.  We have found a bug with the EDIT command on the latest nightly build where the EDIT command makes an "engine" noise and locks up the computer.  However in the firmware default-v0.88 it works as intended.  I prefer this latest build because the PLAY command does not seem to function at all in firmware-default-v0.88.

Thank you, Sir!

**Comment by uli** [comment]
Please verify that this works in the latest nightly build and, if so, close the bug.

**Comment by bitartrate** [comment]
Thank you, Uli.  EDIT no longer crashes system and seems to function properly.
